#Programa7
var1=input("Introduce el número1 ")
var2=input("Introduce el número2 ")
suma=int(var1)+int(var2)
resta=int(var1)-int(var2)
multiplicación=int(var1)*int(var2)
división=int(var1)/int(var2)
exponente=int(var1)**int(var2)
división_entera=int(var1)//int(var2)
print(f"La suma de operador1 y operador 2 és: {suma}")
print(f"La resta de operador1 y operador 2 és: {resta}")
print(f"La multiplicación de operador1 y operador 2 és: {multiplicación}")
print(f"La división de operador1 y operador 2 és: {división}")
print(f"El exponente de operador1 y operador 2 és: {exponente}")
print(f"La división entera de operador1 y operador 2 és: {división_entera}")